### ISSUE TITLE
Bug - scrolling iframe causes overlays to go haywire

### ISSUE THREAD

**Issue by birdsarah** [mozilla-applied-ml/fta#28]
If I scroll in the iframe. Things get very squirly with the overlays. Hopefully I didn't break this.

Would you mind taking a look @reuben?

**Comment by reuben** [comment]
Can't reproduce your exact description, but things do get wonky when I scroll the parent window. Gonna take a look.

**Comment by birdsarah** [comment]
Yes. That sounds very plausible - I was probably always scrolling the parent slightly. 

I'm also fine with layout solutions - like compacting the new top matter and forcing no scroll in the outer window.

**Comment by birdsarah** [comment]
Confirmed your finding, the error comes in at outer page scroll.

**Comment by birdsarah** [comment]
This is still broken for me.

**Comment by birdsarah** [comment]
meh. it's a little wonky on scroll back up, but it recovers fine so closing again.
