### ISSUE TITLE
Add a DRF API endpoint that takes same inputs as "add sample" view

### ISSUE THREAD

**Issue by birdsarah** [mozilla-applied-ml/fta#33]
Add a django rest framework API that takes just `frozen_page` and `freeze_software` and runs it through the processing code that's already here: https://github.com/mozilla-applied-ml/fta/blob/main/fta/samples/views.py#L97

**Comment by reuben** [comment]
![image](https://user-images.githubusercontent.com/477142/98022056-68643700-1e05-11eb-9311-5db7fd91e378.png)
...but it works: https://github.com/mozilla-applied-ml/fta/commit/16d6d6f7fcf455b6224584397394004c892b51b8

notes should be optional
