### ISSUE TITLE
Fix SinglePage -> SingleFile

### ISSUE THREAD

**Issue by birdsarah** [mozilla-applied-ml/fta#34]
The freezing software is SingleFile (https://github.com/mozilla-applied-ml/SingleFile)

but I keep getting confused and calling it SinglePage. We should make sure everything is "SingleFile"

**Comment by reuben** [comment]
https://github.com/mozilla-applied-ml/fta/commit/dccfc0ef78e907c39e1b4e809ff725a610aa2dc5
